export LD_LIBRARY_PATH="/usr/local/apr/lib:/usr/local/unimrcp/lib"
all: main.c
        export LD_LIBRARY_PATH="/usr/local/apr/lib:/usr/local/unimrcp/lib" && gcc main.c -I/usr/local/unimrcp/include/ -I/usr/local/apr/include/apr-1 -L/usr/local/apr/lib/ -L/usr/local/unimrcp/lib -lunimrcpclient -lapr-1
